name: vijayai_connect
description: Flutter app with Google Mobile Ads (test IDs). Replace with your AdMob IDs for real earnings.
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
